version: '3.5'
services:
  software:
    hostname: '{{.Node.Hostname}}'
    image: google/cadvisor:latest
    networks:
      - internal
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    deploy:
      mode: global
      restart_policy:
        condition: any
        max_attempts: 3    
networks:
  internal:
    name: internal
    external: true 
