version: '3.5'
services:
  software:
    hostname: '{{.Node.Hostname}}'
    image: google/cadvisor:latest
# container_name: cadvisor
# ports:
# - 8080:8080
    networks:
      - internal
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
    - redis
    deploy:
      labels:
        traefik.enable: "true"
        traefik.backend: "cadvisor"
        traefik.docker.network: "internal"
#       traefik.frontend.rule: "Host:tinyrss.leejonchapman.com"
        traefik.web.port: "8080"
#       traefik.frontend.headers.SSLRedirect: "true"
#       traefik.frontend.headers.SSLHost: "tinyrss.leejonchapman.com"        
      placement:
        constraints:
          - node.role == manager
#       mode: global
      restart_policy:
        condition: any
        max_attempts: 3    
networks:
  internal:
    name: internal
    external: true 
